title: Russ Tokuyama
email: russtoku at gmail dot com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  russtoku

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
